"""auto-vote

Revision ID: 406d00bd8c3f
Revises: e1920189378c
Create Date: 2022-01-28 11:35:46.049482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406d00bd8c3f'
down_revision = 'e1920189378c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
